// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJlgHBTLKL-DiOc4r8Hct-9vS6ieNmzv0',
    appId: '1:985118386125:web:49626740cef8bca052c684',
    messagingSenderId: '985118386125',
    projectId: 'readify-f0da0',
    authDomain: 'readify-f0da0.firebaseapp.com',
    storageBucket: 'readify-f0da0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA272Lst8NKjEke2R3WlloikAIVswTmao',
    appId: '1:985118386125:android:2530c26b5186145252c684',
    messagingSenderId: '985118386125',
    projectId: 'readify-f0da0',
    storageBucket: 'readify-f0da0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJNEDCUwCPGujgGZ20_d-GFFHqhrIoMo',
    appId: '1:985118386125:ios:50857c3f3b47662452c684',
    messagingSenderId: '985118386125',
    projectId: 'readify-f0da0',
    storageBucket: 'readify-f0da0.firebasestorage.app',
    androidClientId: '985118386125-d0tpq3ciijah2nfhhj3ksqhc39195cs5.apps.googleusercontent.com',
    iosClientId: '985118386125-sv7aqrpqf5tqsu2o3v05ir1flllgcig8.apps.googleusercontent.com',
    iosBundleId: 'com.example.readify1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJlgHBTLKL-DiOc4r8Hct-9vS6ieNmzv0',
    appId: '1:985118386125:web:77a033773648dbde52c684',
    messagingSenderId: '985118386125',
    projectId: 'readify-f0da0',
    authDomain: 'readify-f0da0.firebaseapp.com',
    storageBucket: 'readify-f0da0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJNEDCUwCPGujgGZ20_d-GFFHqhrIoMo',
    appId: '1:985118386125:ios:50857c3f3b47662452c684',
    messagingSenderId: '985118386125',
    projectId: 'readify-f0da0',
    storageBucket: 'readify-f0da0.firebasestorage.app',
    androidClientId: '985118386125-d0tpq3ciijah2nfhhj3ksqhc39195cs5.apps.googleusercontent.com',
    iosClientId: '985118386125-sv7aqrpqf5tqsu2o3v05ir1flllgcig8.apps.googleusercontent.com',
    iosBundleId: 'com.example.readify1',
  );

}